
## DataTransferBase.py 
class DataTransferBase:
    
    def __init__(self, **kwargs): ...

    def connect(self): ...

    def get_object(self, url_path) -> bytes: ...

    def download(self, url_path, local_path): ...

    def upload(self, local_path, save_path): ...

    def close(self): ...
